determine_value_type – Fyaml
determine_value_type Subroutine
GPL-3.0
44 statements
Source File
public subroutine determine_value_type(node)
Determine value type of node
Checks content and sets appropriate type flags
@param[in,out] node Node to analyze
Arguments
Type Intent Optional Attributes Name
type(yaml_node), intent(inout) :: node
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: i_value
logical, public :: is_int
logical, public :: is_real
logical, public :: l_value
real, public :: r_value
integer, public :: rc
character(len=32), public :: temp_str
Call graph
determine_value_type calls is_int_string, is_real_string, to_lower