initialize_node – Fyaml
initialize_node Subroutine
GPL-3.0
13 statements
Source File
public subroutine initialize_node(node)
Initialize a new YAML node
Sets default values for a newly created node
@param[in,out] node Node to initialize
Arguments
Type Intent Optional Attributes Name
type(yaml_node), intent(inout), pointer :: node
Called by
Call graph
parse_line calls initialize_node
parse_mapping calls initialize_node
parse_sequence calls initialize_node
parse_flow_form calls parse_mapping, parse_sequence
parse_yaml calls parse_line