parse_flow_form – Fyaml
parse_flow_form Subroutine
GPL-3.0
22 statements
Source File
public subroutine parse_flow_form(line, node)
Parse flow-style YAML syntax
Handles flow-style sequences [...] and mappings {...}
@param[in] line Input containing flow syntax @param[in,out] node Node to store parsed content
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
type(yaml_node), intent(inout), pointer :: node
Calls
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: content
integer, public :: end
integer, public :: pos
integer, public :: start
Call graph
parse_flow_form calls parse_mapping, parse_sequence
parse_mapping calls initialize_node
parse_sequence calls initialize_node