parse_line – Fyaml
parse_line Subroutine
GPL-3.0
97 statements
Source File
public subroutine parse_line(line, doc, status)
Parse a single line of YAML content
Processes a line and updates document structure. Handles: - Indentation - Sequence items - Key-value pairs - Nested structures
@param[in] line Input line @param[in,out] doc Document being built @param[out] status Status code
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
type(yaml_document), intent(inout) :: doc
integer, intent(out) :: status
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: current_indent
type(yaml_node), public, pointer :: current_node
character(len=256), public :: debug_msg
integer, public :: io_stat
logical, public :: is_sequence_item
character(len=:), public, allocatable :: local_line
type(yaml_node), public, pointer :: new_node
integer, public :: parent_indent
type(yaml_node), public, pointer :: parent_node
integer, public :: pos
Call graph
parse_line calls count_leading_spaces, debug_print, initialize_node
parse_yaml calls parse_line